#
# The MIT License (MIT)
#
# Copyright 2014 Author and Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

notifications:
    email: false

git: 
    depth: 1

language: objective-c

before_script:
    # Update Brew Packages
    - brew update
    # Install Apache Ant
    - brew install ant
    # Install Adobe AIR SDK
    - brew install adobe-air-sdk
    - "export AIR_HOME=/usr/local/opt/adobe-air-sdk/libexec"    
    # Install Google Android SDK
    - brew install android-sdk
    - android list sdk -a -e -u
    - echo yes | android update sdk --filter tools,platform-tools,android-19,build-tools-19.1.0 --force --no-ui > /dev/null
    - android list sdk -a -e -u
    - "export ANDROID_HOME=/usr/local/opt/android-sdk"
    
script:
    - xctool -project NativeiOS/QRZBar.xcodeproj -scheme QRZBar build
    - ant